name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/format-and-lint.yml

  test:
    uses: ./.github/workflows/run-tests.yml

  archive:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-archive.yml
    secrets: inherit
